name: Event CID Add

on:
  repository_dispatch:
    types: [cid-add]

jobs:
  cid_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Prepare and save CID file for the repo
        run: |
          CID="${{ steps.w3up.outputs.cid }}"
          REPO_NAME="${{ github.event.client_payload.repo }}"
          CID_FILE="${REPO_NAME}.txt"

          echo $CID > $CID_FILE

      - name: Commit and push the CID file using Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add "${REPO_NAME}.txt"

          git commit -m "Add CID for ${{ github.event.client_payload.repo }}"

          git push origin ${{ github.head_ref }}
