name: Event CID Remove Last

on:
  repository_dispatch:
    types: [cid-rmlast]

jobs:
  cid_rmlast:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 23
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install w3cli globally
        run: npm install -g @web3-storage/w3cli

      - name: Remove the CID file for the repo
        run: |
          echo "Removing last CID of repo ${{ github.event.client_payload.repo }}"
          cat "${{ github.event.client_payload.repo }}.txt.old"

      - run: w3 rm "$(cat ${{ github.event.client_payload.repo }}.txt.old)"
        env:
          W3_PRINCIPAL: ${{ secrets.W3_PRINCIPAL }}

