name: Event CID Remove Last

on:
  repository_dispatch:
    types: [cid-rmlast]

permissions:
  contents: write

jobs:
  cid_rmlast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: npm install -g @web3-storage/w3cli
        shell: bash

      - run: w3 rm "$(cat ${{ github.event.client_payload.repo }}.txt.old)"
        env:
          W3_PRINCIPAL: ${{ secrets.W3_PRINCIPAL }}
        shell: bash

      - name: Remove the CID file for the repo
        run: |
          echo "Removing last CID of repo ${{ github.event.client_payload.repo }}"
          cat "${{ github.event.client_payload.repo }}.txt.old"

      - name: Commit and push the removal of the CID file using Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add "${{ github.event.client_payload.repo }}.txt"

          git commit -m "Remove CID file for ${{ github.event.client_payload.repo }}"

          git push origin ${{ github.head_ref }}
