name: Event CID Add

on:
  repository_dispatch:
    types: [cid-add]

permissions:
  contents: write

jobs:
  cid_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Prepare and save CID file for the repo
        run: |
          echo "Preparing to save new CID ${{ github.event.client_payload.cid }} to repo ${{ github.event.client_payload.repo }}"
          mv -f "${{ github.event.client_payload.repo }}.txt" "${{ github.event.client_payload.repo }}.txt.old"
          echo "${{ github.event.client_payload.cid }}" > "${{ github.event.client_payload.repo }}.txt"

      - name: Commit and push the CID file using Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add "${{ github.event.client_payload.repo }}.txt"
          git add "${{ github.event.client_payload.repo }}.txt.old"

          if git diff --cached --quiet; then
              echo "No changes to commit."
              exit 0
          fi

          git commit -m "Add CID for ${{ github.event.client_payload.repo }}"

          git push
