name: Event CID Remove Last

on:
  repository_dispatch:
    types: [cid-rmlast]

jobs:
  cid_rmlast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Remove the CID file for the repo
        run: |
          echo "Preparing to remove last CID to repo ${{ github.event.client_payload.repo }}"
          if [[ -f "${{ github.event.client_payload.repo }}.txt" ]]; then
            rm "${{ github.event.client_payload.repo }}.txt"
          fi

      - name: Commit and push the removal of the CID file using Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add "${{ github.event.client_payload.repo }}.txt"

          git commit -m "Remove CID file for ${{ github.event.client_payload.repo }}"

          git push origin ${{ github.head_ref }}
